MNepalWeb/MNepalWeb/Controllers/UserSetupController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web.Mvc;
using MNepalWeb.Models;
using MNepalWeb.Utilities;
using System.Web.SessionState;
using MNepalWeb.Helper;

namespace MNepalWeb.Controllers
{
    [SessionState(SessionStateBehavior.Required)]
    public class UserSetupController : Controller
    {
        ///<summary>
        /// Manage Admin Profiles
        ///</summary>
        ///
        // GET: UserSetup
        public ActionResult Index()
        {
            //string userName = (string)Session["LOGGED_USERNAME"];
            string clientCode = (string)Session["LOGGEDUSER_ID"];
            string name = (string)Session["LOGGEDUSER_NAME"];
            string userType = (string)Session["LOGGED_USERTYPE"];
            //Check Role link start          
            string methodlink = System.Reflection.MethodBase.GetCurrentMethod().Name;
            RoleChecker roleChecker = new RoleChecker();
            bool checkRole = roleChecker.checkRole(methodlink, clientCode);
            //Check Role link end


            TempData["userType"] = userType;

            if (TempData["userType"] != null&& checkRole)
            {
                ViewData["userType"] = TempData["userType"];
                ViewBag.UserType = TempData["userType"];
                ViewBag.Name = name;

                List<UserProfilesInfo> userProfilesList = new List<UserProfilesInfo>();
                DataTable dtUserProfile = UserProfileUtils.GetAdminProfile();

                foreach (DataRow row in dtUserProfile.Rows)
                {
                    UserProfilesInfo userobj = new UserProfilesInfo
                    {
                        UPID = row["ProfileCode"].ToString(),
                        ProfileName = row["ProfileName"].ToString(),
                        ProfileDesc = row["ProfileDesc"].ToString(),
                        UserProfileStatus = row["ProfileStatus"].ToString(),
                        MenuAssignId = row["ProfileGroup"].ToString()
                    };

                    userProfilesList.Add(userobj);
                }
                return View(userProfilesList);
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        /// <summary>
        /// Create Admin Profile
        /// </summary>
        /// <returns></returns>
        /// 
        // GET: UserSetup/CreateAdminProfile
        [HttpGet]
        public ActionResult CreateAdminProfile()
        {
            //string userName = (string)Session["LOGGED_USERNAME"];
            string clientCode = (string)Session["LOGGEDUSER_ID"];
            string name = (string)Session["LOGGEDUSER_NAME"];
            string userType = (string)Session["LOGGED_USERTYPE"];
            //Check Role link start          
            string methodlink = System.Reflection.MethodBase.GetCurrentMethod().Name; //get MethodName
            RoleChecker roleChecker = new RoleChecker();
            bool checkRole = roleChecker.checkRole(methodlink, clientCode);
            //Check Role link end
            TempData["userType"] = userType;

            if (TempData["userType"] != null&& checkRole)
            {
                ViewData["userType"] = TempData["userType"];
                ViewBag.UserType = TempData["userType"];
                ViewBag.Name = name;

                if (TempData["adminprofile_messsage"] != null)
                {
                    ViewData["adminprofile_messsage"] = TempData["adminprofile_messsage"];
                    ViewData["message_class"] = TempData["message_class"];
                }

                return View();
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        /// <summary>
        /// Create Admin Profile Inserted
        /// </summary>
        /// <param name="collection"></param>
        /// <returns></returns>
        /// 
        // POST: UserSetup/CreateAdminProfile
        [HttpPost]
        public ActionResult CreateAdminProfile(FormCollection collection)
        {
            //string userName = (string)Session["LOGGED_USERNAME"];
            //string clientCode = (string)Session["LOGGEDUSER_ID"];
            string name = (string)Session["LOGGEDUSER_NAME"];
            string userType = (string)Session["LOGGED_USERTYPE"];

            bool result = false;

            TempData["userType"] = userType;
            string errorMessage = string.Empty;

            if (TempData["userType"] != null)
            {
                ViewData["userType"] = TempData["userType"];
                ViewBag.UserType = TempData["userType"];
                ViewBag.Name = name;

                UserProfilesInfo userInfo = new UserProfilesInfo
                {
                    ProfileName = collection["ProfileName"] ?? string.Empty,
                    ProfileDesc = collection["ProfileDesc"] ?? string.Empty,

                    CanAdmin = collection["checkallAdmin"] ?? string.Empty,
                    CanAdminReg = collection["chkARegistration"] ?? string.Empty,
                    CanAdminModify = collection["chkAModification"] ?? string.Empty,
                    CanAPwdReset = collection["chkAPwdReset"] ?? string.Empty,

                    CanCust = collection["checkallCustomer"] ?? string.Empty,
                    CanCReg = collection["chkCRegister"] ?? string.Empty,
                    CanCApprove = collection["chkCApprove"] ?? string.Empty,
                    CanCModify = collection["chkCModify"] ?? string.Empty,
                    CApproveModify = collection["chkApproveModify"] ?? string.Empty,
                    CStatus = collection["chkCustomerStatus"] ?? string.Empty,
                    CRejectedList = collection["chkCRejectedList"] ?? string.Empty,
                    CPinReset = collection["chkPinReset"] ?? string.Empty,
                    CApprovePinReset = collection["chkAPinReset"] ?? string.Empty,
                    CanCDelete = collection["chkCDelete"] ?? string.Empty,
                    CApproveDelete = collection["chkApproveDelete"] ?? string.Empty,
                    CUnBlockService = collection["chkCUnBlockService"] ?? string.Empty,
                    CApproveUnblock = collection["chkCApproveUnBlock"] ?? string.Empty,
                    CCharge = collection["chkCustCharge"] ?? string.Empty,
                    CApproveRenewCharge = collection["chkCApproveRC"] ?? string.Empty,

                    BranchSetup = collection["checkallBranchSetup"] ?? string.Empty,
                    BranchRegistration = collection["chkBranchRegister"] ?? string.Empty,
                    BranchModification = collection["chkBranchModify"] ?? string.Empty,
                    BranchStatus = collection["chkBranchStatus"] ?? string.Empty,

                    AcTypeSetup = collection["chkAcType"] ?? string.Empty,
                    AcTypeSetupm = collection["chkAcTypem"] ?? string.Empty,

                    MNepalPay = collection["checkallMNepalPay"] ?? string.Empty,
                    ManageService = collection["chkManageServices"] ?? string.Empty,
                    CheckStatus = collection["chkCheckStatus"] ?? string.Empty,
                    Cancellation = collection["chkCancellation"] ?? string.Empty,
                    UserSetup = collection["checkallUserSetup"] ?? string.Empty,
                    UCreateAdminProfile = collection["chkCAdminProfile"] ?? string.Empty,
                    UModifyAdminProfile = collection["chkMAdminProfile"] ?? string.Empty,
                    UCreateCustProfile = collection["chkCCustomerProfile"] ?? string.Empty,
                    UModifyCustProfile = collection["chkMCustProfile"] ?? string.Empty,
                    Request = collection["checkallRequest"] ?? string.Empty,
                    RChequeBookList = collection["chkChkList"] ?? string.Empty,
                    RStmtList = collection["chkStmtList"] ?? string.Empty,
                    RComplainList = collection["chkComplainList"] ?? string.Empty,
                    RRecommandationList = collection["chkRecomList"] ?? string.Empty,
                    Messaging = collection["checkallMsg"] ?? string.Empty,
                    MUncastMsg = collection["chkUnicastMsg"] ?? string.Empty,
                    MBulkMsg = collection["chkBulkMsg"] ?? string.Empty,
                    MResendMsg = collection["chkResendMsg"] ?? string.Empty,
                    Report = collection["checkallReport"] ?? string.Empty,
                    ReSmsInOut = collection["chkRSMS"] ?? string.Empty,
                    ReChequeBookRequest = collection["chkRCheckBookReq"] ?? string.Empty,
                    ReStmtRequest = collection["chkRStmtReq"] ?? string.Empty,
                    ReRegisteredCustomer = collection["chkRRegisterCust"] ?? string.Empty,
                    ReAdminActivities = collection["chkRAdminActivities"] ?? string.Empty,
                    ReCustActivities = collection["chkRCustAct"] ?? string.Empty,
                    ReMerchantPayment = collection["chkRMerchantPay"] ?? string.Empty,
                    ReMNepalPayTran = collection["chkRMNepalPayTran"] ?? string.Empty,
                    ReMNepalPayCancel = collection["chkRPayCancel"] ?? string.Empty,
                    ReCardRequest = collection["chkRCardRequest"] ?? string.Empty,
                    ReServicePayments = collection["chkServicePayments"] ?? string.Empty,
                    ReTransactionDetail = collection["chkRTranDetail"] ?? string.Empty,
                    ReAdminDetail = collection["chkRAdminDetail"] ?? string.Empty,
                    ReCharge = collection["chkCharge"] ?? string.Empty,
                    ReMNepalPayReport = collection["chkRTopupReport"] ?? string.Empty,
                    Payee = collection["checkallPayee"] ?? string.Empty,

MNepalWeb/MNepalWeb/Views/UserSetup/Index.cshtml
@{
    ViewBag.Title = "Index";
}

@model List<MNepalWeb.Models.UserProfilesInfo>
<!-- =============================================== -->
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Manage Admin
        <small>Profiles</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Dashboard</a></li>
        <li class="active"> Manage Admin Profiles</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <!-- Main row -->
    <div class="row">

        <!-- Start Form -->
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Manage Admin Profiles</h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">

                    <div class="row">
                        <div class="col-md-10">

                            <table id="t01" class="table table-bordered table-striped">
                                <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>Description</th>
                                    <th>Status</th>
                                    <th colspan="3">Action</th>
                                </tr>
                                </thead>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            @item.ProfileName
                                        </td>
                                        <td>
                                            @item.ProfileDesc
                                        </td>
                                        <td>
                                            @if (item.UserProfileStatus == "Active")
                                            {
                                                <span class="badge bg-green-active"> @item.UserProfileStatus </span>
                                            }
                                            else
                                            {
                                                <span class="badge bg-red-active"> @item.UserProfileStatus </span>
                                            }
                                        </td>
                                        <td style="width: 10px;">
                                            <a href="@Url.Action("EditAdminProfileSetup", "UserSetup", new {profileCode = @item.UPID})"><i class="fa fa-pencil fa-fw" title="Edit"></i></a>
                                        </td>
                                        <td style="width: 10px;">
                                            <a href="@Url.Action("ViewAdminProfileSetup", "UserSetup", new {profileCode = @item.UPID})"><i class="fa fa-eye" title="View"></i></a>
                                        </td>
                                        @*<td  style="width:10px;">
                        <a href="@Url.Action("DeleteAdminSetup", "UserSetup", new { menuAssignId = @item.MenuAssignId } )"><i class="fa fa-trash"></i></a>
                    </td>*@
                                    </tr>

                                }

                            </table>

                        </div>
                    </div>

                </div>
            </div>
        </div>
        <!--End Form -->

    </div>
    <!-- /.row -->
</section>
<!-- /.content -->
<!-- page script -->
@section scripts{
    <script>
        $(function() {
            $('#t01').DataTable();
        });
    </script>
}
<!-- =============================================== -->