MNepalWeb/CustApp/Models/ShoppingMallLogin.cs
namespace CustApp.Models
{
    public class ShoppingMallLogin
    {
        public string MerchantId { get; set; }
        public string ItemCode { get; set; }
        public string Price { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Pin { get; set; }
    }
}

MNepalWeb/CustApp/Controllers/ShoppingMallLoginController.cs
using CustApp.Helper;
using CustApp.Models;
using CustApp.Utilities;
using Newtonsoft.Json;
using System;
using System.Configuration;
using System.Data;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using static CustApp.Models.CIPS;

namespace CustApp.Controllers
{
    public class ShoppingMallLoginController : Controller
    {
        #region Index
        public ActionResult Index()
        {
            ViewBag.merchantId = Request["merchantId"];
            ViewBag.itemCode = Request["itemCode"];
            ViewBag.price = Request["price"];

            Session["MerchantId"] = ViewBag.merchantId;
            Session["ItemCode"] = ViewBag.itemCode;
            Session["Price"] = ViewBag.price;
            return View();
        }
        #endregion

        #region LoginMerchant
        [HttpPost]
        public ActionResult LoginMerchant(ShoppingMallLogin merchant)
        {
            var userName = merchant.UserName;
            Session["UserName"] = userName;
            var password = HashAlgo.Hash(merchant.Password);
            int responseCode = 0;
            string respmsg = "Unauthorized";
            DataTable dtableBlockUserWrongPwd = LoginUtils.GetBlockTime(userName);
            if (dtableBlockUserWrongPwd != null && dtableBlockUserWrongPwd.Rows.Count > 0)
            {
                DataTable dtableUser = LoginUtils.GetLoginInfo(userName, password);
                if (dtableUser.Rows.Count == 0)
                {
                    return Json(new { responseCode = responseCode, responseText = respmsg },
                    JsonRequestBehavior.AllowGet);
                }
                if (dtableUser != null && dtableUser.Rows.Count > 0)
                {
                    dtableBlockUserWrongPwd = LoginUtils.ResetPasswordTry(userName);
                    if (dtableBlockUserWrongPwd == null)
                    {
                        return Json(new { responseCode = 200, responseText = "Success" },
                           JsonRequestBehavior.AllowGet);
                    }
                }
            }


            return View();
        }
        #endregion      

        #region LoginMerchantDetails
        public async Task<ActionResult> LoginMerchantDetails()
        {
            ViewBag.merchantId = Session["MerchantId"];
            ViewBag.itemCode = Session["ItemCode"];
            ViewBag.price = Session["Price"];

            return View();
        }
        #endregion

        #region LoginMerchantVerifyPin
        public async Task<ActionResult> LoginMerchantVerifyPin(ShoppingMallLogin shoppingMallLogin)
        {
            HttpResponseMessage _res = new HttpResponseMessage();
            var cipsObject = new CheckPin
            {
                userName = Session["UserName"].ToString(),
                pin = shoppingMallLogin.Pin
            };

            //specify to use TLS 1.2 as default connection
            ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12 | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls;

            // Serialize our concrete class into a JSON String
            var stringPayload = await Task.Run(() => JsonConvert.SerializeObject(cipsObject));
            // Wrap our JSON inside a StringContent which then can be used by the HttpClient class
            var httpContent = new StringContent(stringPayload, Encoding.UTF8, "application/json");
            using (HttpClient httpClient = new HttpClient())
            {
                var UserName = ConfigurationManager.AppSettings["BasicAuthUserName"];
                var UserPassword = ConfigurationManager.AppSettings["BasicAuthPassword"];
                var APIBaseURL = ConfigurationManager.AppSettings["APIBaseURL"];

                var byteArray = Encoding.ASCII.GetBytes(UserName + ":" + UserPassword);
                httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Basic", Convert.ToBase64String(byteArray));

                _res = await httpClient.PostAsync(APIBaseURL + "ConnectIPS/CheckPin", httpContent);
                string responseBody = _res.StatusCode.ToString() + " ," + await _res.Content.ReadAsStringAsync();
                _res.ReasonPhrase = responseBody;
                string errorMessage = string.Empty;
                int responseCode = 0;
                string message = string.Empty;
                string responsetext = string.Empty;
                string responseMessage = string.Empty;
                bool result = false;
                string ava = string.Empty;
                string avatra = string.Empty;
                string avamsg = string.Empty;
                try
                {
                    if (_res.IsSuccessStatusCode)
                    {
                        result = true;
                        responseCode = (int)_res.StatusCode;
                        responsetext = await _res.Content.ReadAsStringAsync();
                        message = _res.Content.ReadAsStringAsync().Result;
                        string respmsg = "";
                        string couponNo = "";
                        if (!string.IsNullOrEmpty(message))
                        {
                            JavaScriptSerializer ser = new JavaScriptSerializer();
                            var json = ser.Deserialize<ConnectIPSResponse>(responsetext);
                            int code = Convert.ToInt32(json.cipsBatchResponse.responseCode);
                            respmsg = json.cipsBatchResponse.responseMessage;
                        }
                        return Json(new { responseCode = responseCode, responseText = respmsg, rechargePin = couponNo },
                        JsonRequestBehavior.AllowGet);
                    }
                    else
                    {
                        result = false;
                        responseCode = (int)_res.StatusCode;
                        responsetext = await _res.Content.ReadAsStringAsync();
                        JavaScriptSerializer ser = new JavaScriptSerializer();
                        var json = ser.Deserialize<CheckPin>(responsetext);

                        return Json(new { responseCode = responseCode, responseText = json.message },
                        JsonRequestBehavior.AllowGet);
                    }
                }
                catch (Exception ex)
                {
                    return Json(new { responseCode = "400", responseText = ex.Message },
                        JsonRequestBehavior.AllowGet);
                }
            }
        }
        #endregion
    }
}

MNepalWeb/CustApp/Views/ShoppingMallLogin/Index.cshtml
@{
    ViewBag.Title = "Index";
}

@using (Html.BeginForm("LoginMerchant", "ShoppingMallLogin", FormMethod.Post, new { @id = "ShoppingMall", @name = "ShoppingMall", @class = "form-horizontal", enctype = "multipart/form-data" }))
{
    <div class="col-md-offset-5">
        <div class="row">
            <div class="col-md-6">
                <label>MerchantId</label><span>
                    <input type="text" value="@ViewBag.merchantId" name="txtMerchantId" disabled="disabled" />
                </span>
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-6">
                <label>ItemCode</label><span>
                    <input type="text" value="@ViewBag.itemCode" name="txtItemCode" disabled="disabled" />
                </span>
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-6">
                <label>Price</label><span>
                    <input type="text" value="@ViewBag.price" name="txtPrice" disabled="disabled" />
                </span>
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-6">
                <label>UserName</label><span>
                    <input type="text" id="userName" name="txtUserName" class="form-control" placeholder="UserName" onpaste="return false" />
                </span>
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-6">
                <label>Password</label><span>
                    <input type="password" id="password" name="txtPassword" class="form-control" placeholder="Password" onpaste="return false" />
                </span>
            </div>
        </div>
        <br />

        <div class="row">
            <div class="col-md-6">
                <input type="submit" class="btn btn-blue btn-big col-md-5" id="btnLogin" value="Login" />
                @*<input type="submit" class="btn btn-blue btn-big col-md-5" name="btnCommand" value="Submit" id="btnSubmit" />*@
            </div>
        </div>
        <br />
    </div>

    <!-- Failure modal -->
    <div class="modal fade common-modal" id="failureModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-body text-center">
                    <div class="success-icon">
                        <img src="~/Content/assets/img/denied-cross.svg" alt="denied-cross">
                    </div>
                    <p style="color: #E31837; font-size: 1.111rem; font-weight: 700;">@*Error!*@</p>
                    <span style="color: #E31837; font-size: 1.111rem; font-weight: 700;" id="message"></span>
                    <br /> <br />
                    <button type="button" class="btn btn-blue" data-dismiss="modal" style="width:80%">OK</button>
                </div>
            </div>
        </div>
    </div>

    <!-- Failure modal -->
    <div class="modal fade common-modal" id="failureBankModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-body text-center">
                    <div class="success-icon">
                        <img src="~/Content/assets/img/denied-cross.svg" alt="denied-cross">
                    </div>
                    <p style="color: #E31837; font-size: 1.111rem; font-weight: 700;">@*Error!*@</p>
                    <span style="color: #E31837; font-size: 1.111rem; font-weight: 700;" id="message1"></span>
                    <br /> <br />
                    <button type="button" class="btn btn-blue" data-dismiss="modal" style="width:80%">OK</button>
                </div>
            </div>
        </div>
    </div>

    <!-- Failure modal session expired -->
    <div class="modal fade common-modal" id="failureModalSessionExpired" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-body text-center">
                    <div class="success-icon">
                        <img src="~/Content/assets/img/denied-cross.svg" alt="denied-cross">
                    </div>
                    <p style="color: #E31837; font-size: 1.111rem; font-weight: 700;">@*Error!*@</p>
                    <span style="color: #E31837; font-size: 1.111rem; font-weight: 700;">Session expired. Please login again</span>
                    <br /> <br />
                    <button type="button" class="btn btn-blue" data-dismiss="modal" style="width:80%">OK</button>
                </div>
            </div>
        </div>
    </div>

}

@section scripts{
    <script type="text/javascript">


        $('#btnLogin').click(function (e) {
                e.preventDefault();
                debugger;
               var merchantId = $("[name='txtMerchantId']").val();
               var itemCode = $("[name='txtItemCode']").val();
               var price = $("[name='txtPrice']").val();
               var username = $("[name='txtUserName']").val();
               var password = $("[name='txtPassword']").val();

               if ((merchantId != "") && (itemCode != "") && (price != "")) {

                   var dataToPost = {
                       merchantId: merchantId,
                       itemCode: itemCode,
                       price: price,
                       username: username,
                       password: password
                };

                e.preventDefault(); //prevent the default action
                $.ajax({
                    url: '@Url.Action("LoginMerchant", "ShoppingMallLogin")',
                    type: "POST",
                    data:
                    {
                        merchant: dataToPost
                    },
                    async: true,
                    success: function (data) {
                        debugger;
                        if (data.responseCode == "200") {
                            var url = '@Url.Action("LoginMerchantDetails", "ShoppingMallLogin")';
                            window.location.href = url;
                        }
                        //display error message
                        else {
                            $("#ajaxResponse").html("");
                            $("#message").html("");
                            $("#message").append(data.responseText);
                            if (data.responseText == "Session expired. Please login again") {
                                $('#failureModalSessionExpired').modal("show");
                            }
                            else {
                                $('#failureModal').modal("show");
                            }

                        }
                    },
                    error: function (jqXHR, textStatus, errorThrown) {
                        alert('Failed to retrieve.');
                        $("#message").html("");
                        $("#message").append(jqXHR.responseText);
                        $('#failureModal').modal("show");

                    },
                    //capture the request before it was sent to server
                    beforeSend: function (jqXHR, settings) {
                        $(".preload").show();
                        //adding some Dummy data to the request
                        settings.data += "&dummyData=whatever";
                        //disable the button until we get the response
                        $('#btnLogin').attr("disabled", true);
                    },
                    complete: function (jqXHR, textStatus) {
                        //enable the button
                        $('.preload').hide();
                        $('#btnLogin').attr("disabled", false);
                    }
                });

            }
            else {
                checkValidation();
                $("#message").html("");
                $("#message").append("Please Enter the required fields.");
                $('#failureModal').modal("show");

            }
        });

        $('#btnSubmit').click(function (e) {
                e.preventDefault();
                debugger;
               var merchantId = $("[name='txtMerchantId']").val();
               var itemCode = $("[name='txtItemCode']").val();
               var price = $("[name='txtPrice']").val();
               var username = $("[name='txtUserName']").val();
               var password = $("[name='txtPassword']").val();
               var pin = $("[name='txtPIN']").val();

               if ((merchantId != "") && (itemCode != "") && (price != "")) {

                   var dataToPost = {
                       merchantId: merchantId,
                       itemCode: itemCode,
                       price: price,
                       username: username,
                       password: password,
                       pin: pin
                };

                e.preventDefault(); //prevent the default action
                $.ajax({
                    url: '@Url.Action("LoginMerchantVerifyPin", "ShoppingMallLogin")',
                    type: "POST",
                    data:
                    {
                        shoppingMallLogin: dataToPost
                    },
                    async: true,
                    success: function (data) {
                        debugger;
                        if (data.responseCode == "200") {
                            var url = '@Url.Action("LoginMerchantDetails", "ShoppingMallLogin")';
                            window.location.href = url;

                        }
                        //display error message
                        else {
                            $("#ajaxResponse").html("");
                            $("#message").html("");
                            $("#message").append(data.responseText);
                            if (data.responseText == "Session expired. Please login again") {
                                $('#failureModalSessionExpired').modal("show");
                            }
                            else {
                                $('#failureModal').modal("show");
                            }

                        }
                    },
                    error: function (jqXHR, textStatus, errorThrown) {
                        alert('Failed to retrieve.');
                        $("#message").html("");
                        $("#message").append(jqXHR.responseText);
                        $('#failureModal').modal("show");

                    },
                    //capture the request before it was sent to server
                    beforeSend: function (jqXHR, settings) {
                        $(".preload").show();
                        //adding some Dummy data to the request
                        settings.data += "&dummyData=whatever";
                        //disable the button until we get the response
                        $('#btnSubmit').attr("disabled", true);
                    },
                    complete: function (jqXHR, textStatus) {
                        //enable the button
                        $('.preload').hide();
                        $('#btnSubmit').attr("disabled", false);
                    }
                });

            }
            else {
                checkValidation();
                $("#message").html("");
                $("#message").append("Please Enter the required fields.");
                $('#failureModal').modal("show");

            }
        });

    </script>
}

MNepalWeb/CustApp/Views/ShoppingMallLogin/LoginMerchantDetails.cshtml
@{
    ViewBag.Title = "LoginMerchantDetails";
}

@using (Html.BeginForm("", "", FormMethod.Post, new { @id = "ShoppingMall", @name = "ShoppingMall", @class = "form-horizontal", enctype = "multipart/form-data" }))
{
    <div class="col-md-offset-5">
        <div class="row">
            <div class="col-md-6">
                <label>MerchantId</label><span>
                    <input type="text" value="@ViewBag.merchantId" name="txtMerchantId" disabled="disabled" />
                </span>
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-6">
                <label>ItemCode</label><span>
                    <input type="text" value="@ViewBag.itemCode" name="txtItemCode" disabled="disabled" />
                </span>
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-6">
                <label>Price</label><span>
                    <input type="text" value="@ViewBag.price" name="txtPrice" disabled="disabled" />
                </span>
            </div>
        </div>
        <br />

        <div class="row">
            <div class="col-md-6">
                <label>T-PIN</label><span>
                    <input type="text" name="txtPIN" id="TPIN" />
                </span>
            </div>
        </div>
        <br />

        <div class="row">
            <div class="col-md-6">
                <input type="submit" class="btn btn-blue btn-big col-md-5" name="btnCommand" value="Pay" id="btnSubmit" />
            </div>
        </div>
        <br />
    </div>

    <!-- Failure modal -->
    <div class="modal fade common-modal" id="failureModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-body text-center">
                    <div class="success-icon">
                        <img src="~/Content/assets/img/denied-cross.svg" alt="denied-cross">
                    </div>
                    <p style="color: #E31837; font-size: 1.111rem; font-weight: 700;">@*Error!*@</p>
                    <span style="color: #E31837; font-size: 1.111rem; font-weight: 700;" id="message"></span>
                    <br /> <br />
                    <button type="button" class="btn btn-blue" data-dismiss="modal" style="width:80%">OK</button>
                </div>
            </div>
        </div>
    </div>

    <!-- Failure modal -->
    <div class="modal fade common-modal" id="failureBankModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-body text-center">
                    <div class="success-icon">
                        <img src="~/Content/assets/img/denied-cross.svg" alt="denied-cross">
                    </div>
                    <p style="color: #E31837; font-size: 1.111rem; font-weight: 700;">@*Error!*@</p>
                    <span style="color: #E31837; font-size: 1.111rem; font-weight: 700;" id="message1"></span>
                    <br /> <br />
                    <button type="button" class="btn btn-blue" data-dismiss="modal" style="width:80%">OK</button>
                </div>
            </div>
        </div>
    </div>

    <!-- Failure modal session expired -->
    <div class="modal fade common-modal" id="failureModalSessionExpired" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-body text-center">
                    <div class="success-icon">
                        <img src="~/Content/assets/img/denied-cross.svg" alt="denied-cross">
                    </div>
                    <p style="color: #E31837; font-size: 1.111rem; font-weight: 700;">@*Error!*@</p>
                    <span style="color: #E31837; font-size: 1.111rem; font-weight: 700;">Session expired. Please login again</span>
                    <br /> <br />
                    <button type="button" class="btn btn-blue" data-dismiss="modal" style="width:80%">OK</button>
                </div>
            </div>
        </div>
    </div>

}

@section scripts{
    <script type="text/javascript">
        $('#btnSubmit').click(function (e) {
            e.preventDefault();
            var pin = $("[name='txtPIN']").val();

            if ((pin != ""))
            {
                   var dataToPost = {
                       pin: pin
                };

                e.preventDefault(); //prevent the default action
                $.ajax({
                    url: '@Url.Action("LoginMerchantVerifyPin", "ShoppingMallLogin")',
                    type: "POST",
                    data:
                    {
                        shoppingMallLogin: dataToPost
                    },
                    async: true,
                    success: function (data) {
                        debugger;
                        if (data.responseCode == "200") {
                            var url = 'https://www.google.com/';
                            window.location.href = url;
                        }
                        //display error message
                        else {
                            $("#ajaxResponse").html("");
                            $("#message").html("");
                            $("#message").append(data.responseText);
                            if (data.responseText == "Session expired. Please login again") {
                                $('#failureModalSessionExpired').modal("show");
                            }
                            else {
                                $('#failureModal').modal("show");
                            }

                        }
                    },
                    error: function (jqXHR, textStatus, errorThrown) {
                        alert('Failed to retrieve.');
                        $("#message").html("");
                        $("#message").append(jqXHR.responseText);
                        $('#failureModal').modal("show");

                    },
                    //capture the request before it was sent to server
                    beforeSend: function (jqXHR, settings) {
                        $(".preload").show();
                        //adding some Dummy data to the request
                        settings.data += "&dummyData=whatever";
                        //disable the button until we get the response
                        $('#btnSubmit').attr("disabled", true);
                    },
                    complete: function (jqXHR, textStatus) {
                        //enable the button
                        $('.preload').hide();
                        $('#btnSubmit').attr("disabled", false);
                    }
                });

            }
            else {
                checkValidation();
                $("#message").html("");
                $("#message").append("Please Enter the required fields.");
                $('#failureModal').modal("show");

            }
        });
    </script>
}