MNepalWeb/MNSuperadmin/Models/FinancialReport.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MNSuperadmin.Models
{
    public class FinancialReport
    {
        public string Date { get; set; }
        public string CustomerName { get; set; }
        public string MobileNumber { get; set; }
        public string TargetNumber { get; set; }
        public string TranID { get; set; }
        public string TransactionType { get; set; }
        public string Status { get; set; }
        public string Message { get; set; }
        public string Amount { get; set; }
    }
}

MNepalWeb/MNSuperadmin/Models/MerchantPay.cs
using MNSuperadmin.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MNSuperadmin.Models
{
    public class MerchantPay
    {
        public string StartDate { get; set; }

        public string EndDate { get; set; }

        public string SourceMobileNo { get; set; }

      

        public string Status { get; set; }

        public string MerchantType { get; set; }
        public List<Merchants> MerchantTypeList { get; set; }

        public string MerchantName { get; set; }

        //for Summary Report//
        public string Service { get; set; }

        public string GrpByDate { get; set; }

        //for summary detail report

        public string  Sales { get; set; }

        public string SalesYear { get; set; }

        public string SalesMonth { get; set; }




    }
}

MNepalWeb/MNSuperadmin/Models/NonFinancialReport.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MNSuperadmin.Models
{
    public class NonFinancialReport
    {
        public string Date { get; set; }
        public string CustomerName { get; set; }
        public string MobileNumber { get; set; }
        public string TransID { get; set; }
        public string TransactionType { get; set; }
        public string Status { get; set; }

    }
}

MNepalWeb/MNSuperadmin/Models/TransactionReport.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MNSuperadmin.Models
{
    public class TransactionReport
    {
        public string Date { get; set; }

        public string AgentName { get; set; }

        public string AgentMobileNumber { get; set; }

        public string Services { get; set; }

        public string TransactionCount { get; set; }

        public string Status { get; set; }

        public string CommissionEarned { get; set; }

     
    }
}

MNepalWeb/MNSuperadmin/Controllers/ReportController.cs
using MNSuperadmin.Models;
using MNSuperadmin.UserModels;
using MNSuperadmin.Utilities;
using MNSuperadmin.Helper;
using MNSuperadmin.ViewModel;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data;
using System.Dynamic;
using System.Globalization;
using System.Linq;
using System.Reflection;
using System.Web.Mvc;
using System.Web.SessionState;
using System.Text.RegularExpressions;

namespace MNSuperadmin.Controllers
{
    [SessionState(SessionStateBehavior.Required)]
    public class ReportController : Controller
    {


        #region Super Admin Activities
        [HttpGet]
        public ActionResult SuperAdminActivityReport()
        {
            string userName = (string)Session["LOGGED_USERNAME"];
            string clientCode = (string)Session["LOGGEDUSER_ID"];
            string name = (string)Session["LOGGEDUSER_NAME"];
            string userType = (string)Session["LOGGED_USERTYPE"];

            TempData["userType"] = userType;

            if (TempData["userType"] != null)
            {
                this.ViewData["userType"] = this.TempData["userType"];
                ViewBag.UserType = this.TempData["userType"];
                ViewBag.COC = Session["COC"];
                return View();
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }

        }


        public ContentResult AdminActivityTable(DataTableAjaxPostModel model, string UserName, string BranchCode, string StartDate, string EndDate, string change, string ToExcel)
        {
            if (!Request.IsAjaxRequest())
            {
                Response.Write("Invalid Execution");
                return Content("");
            }

            int filteredResultsCount;
            int totalResultsCount;
            string ParaChanged = "T";
            string convert;
            if (!string.IsNullOrEmpty(StartDate))
            {
                if (!StartDate.IsValidDate())
                {

                    convert = JsonConvert.SerializeObject(new
                    {
                        draw = model.draw,
                        recordsTotal = 0,
                        recordsFiltered = 0,
                        error = "Not valid Start Date"
                    });

                    return Content(convert, "application/json");
                }
                StartDate = DateTime.ParseExact(StartDate, "dd/MM/yyyy", CultureInfo.InvariantCulture)
                                                .ToString("MM/dd/yyyy", CultureInfo.InvariantCulture);
            }

            if (!string.IsNullOrEmpty(EndDate))
            {
                if (!EndDate.IsValidDate())
                {

                    convert = JsonConvert.SerializeObject(new
                    {
                        draw = model.draw,
                        recordsTotal = 0,
                        recordsFiltered = 0,
                        error = "Not valid End Date"
                    });

                    return Content(convert, "application/json");
                }
                EndDate = DateTime.ParseExact(EndDate, "dd/MM/yyyy", CultureInfo.InvariantCulture)
                                                .ToString("MM/dd/yyyy", CultureInfo.InvariantCulture);
            }
            ParaChanged = change;
            var result = new List<MNAdminActivity>();
            if (Session["AdminActivity"] != null && ParaChanged == "F")
            {
                result = Session["AdminActivity"] as List<MNAdminActivity>;
            }
            else
            {
                ReportUserModel rep = new ReportUserModel();
                result = rep.GetSuperAdminActivity(UserName, BranchCode, StartDate, EndDate);
                Session["AdminActivity"] = result;

            }
            if (ToExcel == "T")
            {

                DataTable excel = ToDataTable<MNAdminActivity>(result);
                string Handler = Guid.NewGuid().ToString();
                TempData[Handler] = excel;
                string FileName = DateTime.Now + "_AdminActivity.xls";
                convert = JsonConvert.SerializeObject(new
                {
                    FileGuid = Handler,
                    FileName = FileName
                });
                return Content(convert, "application/json");
            }
            var res = FilterAndSort<MNAdminActivity>(model, result, out totalResultsCount, out filteredResultsCount);
            var resultList = new List<dynamic>();
            foreach (var item in res)
            {
                dynamic resultset = new ExpandoObject();

                resultset.UserName = item.UserName;
                resultset.Name = item.Name;
                resultset.Role = item.Role;
                resultset.BranchCode = item.BranchCode;
                resultset.Description = item.Description;
                resultset.Code = item.Code;
                resultset.Remarks = string.Join(" ", item.Remarks, item.Description);
                resultset.TimeStamp = item.TimeStamp;
                resultList.Add(resultset);
            }
            convert = JsonConvert.SerializeObject(new
            {
                draw = model.draw,
                recordsTotal = totalResultsCount,
                recordsFiltered = filteredResultsCount,
                data = resultList
            });
            return Content(convert, "application/json");

        }
        #endregion

        #region Customer Login Activities
        [HttpGet]
        public ActionResult CustomerLoginActivities()
        {
            string userName = (string)Session["LOGGED_USERNAME"];
            string clientCode = (string)Session["LOGGEDUSER_ID"];
            string name = (string)Session["LOGGEDUSER_NAME"];
            string userType = (string)Session["LOGGED_USERTYPE"];

            TempData["userType"] = userType;

            if (TempData["userType"] != null)
            {
                this.ViewData["userType"] = this.TempData["userType"];
                ViewBag.UserType = this.TempData["userType"];
                ViewBag.COC = Session["COC"];
                return View();
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }

        }


        public ContentResult CustomerLoginActivityTable(DataTableAjaxPostModel model, string UserName, string BranchCode, string StartDate, string EndDate, string change, string ToExcel)
        {
            if (!Request.IsAjaxRequest())
            {
                Response.Write("Invalid Execution");
                return Content("");
            }

            int filteredResultsCount;
            int totalResultsCount;
            string ParaChanged = "T";
            string convert;
            if (!string.IsNullOrEmpty(StartDate))
            {
                if (!StartDate.IsValidDate())
                {

                    convert = JsonConvert.SerializeObject(new
                    {
                        draw = model.draw,
                        recordsTotal = 0,
                        recordsFiltered = 0,
                        error = "Not valid Start Date"
                    });

                    return Content(convert, "application/json");
                }
                StartDate = DateTime.ParseExact(StartDate, "dd/MM/yyyy", CultureInfo.InvariantCulture)
                                                .ToString("MM/dd/yyyy", CultureInfo.InvariantCulture);
            }

            if (!string.IsNullOrEmpty(EndDate))
            {
                if (!EndDate.IsValidDate())
                {

                    convert = JsonConvert.SerializeObject(new
                    {
                        draw = model.draw,
                        recordsTotal = 0,
                        recordsFiltered = 0,
                        error = "Not valid End Date"
                    });

                    return Content(convert, "application/json");
                }
                EndDate = DateTime.ParseExact(EndDate, "dd/MM/yyyy", CultureInfo.InvariantCulture)
                                                .ToString("MM/dd/yyyy", CultureInfo.InvariantCulture);
            }
            ParaChanged = change;
            var result = new List<CustomerLoginLog>();
            if (Session["CustomerLoginLog"] != null && ParaChanged == "F")
            {
                result = Session["CustomerLoginLog"] as List<CustomerLoginLog>;
            }
            else
            {
                ReportUserModel rep = new ReportUserModel();
                result = rep.GetCustomerLoginActivities(UserName, StartDate, EndDate);
                Session["CustomerLoginLog"] = result;

            }
            if (ToExcel == "T")
            {

                DataTable excel = ToDataTable<CustomerLoginLog>(result);
                string Handler = Guid.NewGuid().ToString();
                TempData[Handler] = excel;
                string FileName = DateTime.Now + "_AdminActivity.xls";
                convert = JsonConvert.SerializeObject(new
                {
                    FileGuid = Handler,
                    FileName = FileName
                });
                return Content(convert, "application/json");
            }
            var res = FilterAndSort<CustomerLoginLog>(model, result, out totalResultsCount, out filteredResultsCount);
            var resultList = new List<dynamic>();
            foreach (var item in res)
            {
                dynamic resultset = new ExpandoObject();

                resultset.UserName = item.UserName;
                resultset.Description = item.Description;
                resultset.SNo = item.SNo;
                resultset.Status = item.Status;
                resultset.Date = item.Date;
                resultset.PrivateIP = item.PrivateIP;
                resultList.Add(resultset);
            }

MNepalWeb/MNSuperadmin/Views/Report/AgentViewDetail.cshtml
@{
    ViewBag.Title = "CustomerModifyDetail";
    Layout = null;
}

<!-- Start Data Show in Table -->
<div id="CustomerModifyDetail" class="box box-primary">
    <div class="box-header with-border">
        <h3 class="box-title">Agent Detail</h3>
    </div>
    <!-- /.box-header -->
    <div class="box-body">

        @if (ViewData["dtableAgentStatus"] == null)
        {
            <div class="panel-body"> <b> @ViewBag.Message</b> </div>
        }
        else if (ViewData["dtableAgentStatus"] != null)
        {
            <table class="table table-condensed">
                <thead>
                    <tr>
                        <th>Created Date</th>
                        <th>Mobile Number</th>
                        <th>Agent Name</th>
                        <th>Status</th>
                        <th>Registered By</th>
                        <th>Approved By</th>
                        <th>KYC Status</th>

                        @*<th>Balance</th>
                        <th>Location</th>*@
                        @*<th>View Details</th>*@
                    </tr>
                </thead>
                <tbody>
                    @foreach (System.Data.DataRow dr in (ViewData["dtableAgentStatus"] as System.Data.DataTable).Rows)
                    {
                        
                        <tr>
                            <td> @DateTime.Parse(dr["CreatedDate"].ToString()).ToString("dd/MM/yyyy")</td>
                            <td> @dr["AgentMobileNo"] </td>
                            <td> @dr["AgentName"] </td>
                            <td> @dr["Status"] </td>
                            <td> @dr["RegisteredBy"] </td>
                            <td> @dr["ApprovedBy"] </td>
                            <td> @dr["KYCstatus"] </td>
                            
                            @*<td>@dr["Balance"]</td>
                            <td>@dr["Location"]</td>*@
                            @*<td>
                                <a href="@Url.Action("ViewAgentDetails","Report", new { MobileNo = @dr["AgentMobileNo"] } )">
                                    <i class="fa fa-eye" title="View"></i>
                                </a>
                            </td>*@
                        </tr>
                    } <!-- for each end-->
                </tbody>
            </table>
        }

    </div>
</div>
<!-- End Data Show in Table -->

MNepalWeb/MNSuperadmin/Views/Report/CustomerAccountLog.cshtml
@{
    ViewBag.Title = "Report CustomerLog";
}

<link href="~/Content/plugins/jquery-ui/jquery-ui-1.12.1.custom/jquery-ui.css" rel="stylesheet" />
<section class="content-header">
    <h1>
        Report
        <small>Customer Log</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-user"></i>Report</a></li>
        <li class="active">Customer Log</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <!-- Main row -->
    <div class="row">
        <!-- Start -->
        <div class="col-xs-12">

            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Customer Log</h3>
                </div>
                <!-- /.box-header -->
                @using (Html.BeginForm("CustomerAccountLog", "Report", FormMethod.Get, new { @id = "CustomerAccountLog" }))
                {
                    <div class="box-body">
                        <div class="row">
                            <br />
                            <div class="row">
                                <div class="col-md-6">
                                    @* <span style="color:red">@ViewBag.Error</span>*@
                                </div>
                            </div>
                            <div class="form-group">
                                <div id="MobileNo" class="col-md-4 form-group">
                                    <label>Mobile Number</label>
                                    <div class="input-group">
                                        <div class="input-group-addon">
                                            <i class="glyphicon glyphicon-phone" style="color:royalblue"></i>
                                        </div>
                                        @Html.TextBox("UserName", null, new
                               {
                                   @class = "form-control",
                                   @Id = "UserName",
                                   @required = "Required",
                                   @onkeypress = "return isNumber(event)",
                                   @maxlength = 10@*, @pattern = "^[9][8][0-9]{8}$", @data_bv_regexp_message = "Mobile Number is not in valid Format"*@ })
                                    </div>

                                    @*  <input type="text" class="form-control" id="txtMobileNoID" name="UserName" placeholder="Mobile Number" maxlength="10" onkeypress="return isNumberKey(event)" value="@Model.Parameter.UserName">*@
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-4 form-group">
                                <label>From</label>

                                <div class="input-group">
                                    <div class="input-group-addon">
                                        <i class="fa fa-calendar"></i>
                                    </div>
                                    @Html.TextBox("StartDate", (string)ViewBag.StartDate, new { @class = "form-control", @Id = "StartDate", @Required = "required", @placeholder = "DD/MM/YYYY", @readonly = "readonly" })
                                </div>
                            </div>
                            <div class="col-md-4  form-group">
                                <label>To</label>
                                <div class="input-group">
                                    <div class="input-group-addon">
                                        <i class="fa fa-calendar"></i>
                                    </div>
                                    @Html.TextBox("EndDate", (string)ViewBag.EndDate, new { @class = "form-control", @Id = "EndDate", @Required = "required", @placeholder = "DD/MM/YYYY", @readonly = "readonly" })
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="box-footer">
                        <input type="submit" class="btn btn-primary" id="Search" name="txtSearch" value="Search" />
                    </div>
                }
            </div>
            <!--/.box -box-danger-->
            <div id="data" class="box box-primary">
                <div class="box-body" id="grid">
                    <span class="fa fa-2x fa-file-excel-o pull-right" style="color:green;display:none;" title="To Excel" id="ToExcel"></span>
                    <table id="SearchResultTable" class="table table-striped table-bordered" style="display:none;overflow-x:scroll">
                        <thead>
                            <tr>
                                <th>Transaction Date</th>
                                <th>Service Type</th>
                                <th>Amount</th>
                                <th>Receiver</th>
                                <th>Detail</th>
                                <th>Status</th>
                            </tr>
                        </thead>
                    </table>
                </div>
                <div class="overlay" id="loading" style="display:none;">
                    <i class="fa fa-refresh fa-spin"></i>
                </div>
            </div>
            <!-- /.col-xs--->
            <!-- End-->

        </div>
    </div>
    <!-- /.row -->
</section>

@section scripts{
    <script type="text/javascript">
        $(document).ready(function () {

            var changed = "F";
            $('#UserName, #StartDate, #EndDate').on('input propertychange paste', function () {
                changed = "T";
            });
            var table;
             $('#ToExcel').click(function () {
                 var UserName = $('#UserName').val();
                 var StartDate = $('#StartDate').val();
                 var EndDate = $('#EndDate').val();
                 var Parachanged = changed;
                $.ajax({
                    url: "@Url.Action("CustomerAccountLogTable", "Report")",
                    data: {
                        UserName: UserName,
                        StartDate: StartDate,
                        EndDate: EndDate,
                        change: Parachanged,
                        ToExcel: 'T'
                    },
                    type: 'POST',
                    success: function (data) {
                        var url = "@Url.Action("Download", "Report")";
                        window.location = url + '?fileGuid=' + data.FileGuid
                           + '&filename=' + data.FileName;
                        /*window.open(url + '?fileGuid=' + data.FileGuid
                           + '&filename=' + data.FileName, '_blank');*/
                    },
                    error: function (data) {

                    }


                });
            });
            $('#Search').click(function (e) {
                e.preventDefault();
                changed = "T";
                var UserName = $('#UserName').val();
                if (UserName.trim().length <= 0) {
                    $('#UserName').focus();
                    alertify.error('Please enter mobile number');
                    return;
                }
                var StartDate = $('#StartDate').val();
                var EndDate = $('#EndDate').val();
                var Parachanged = changed;
                if ($.fn.DataTable.isDataTable('#SearchResultTable')) {
                    table.destroy();
                }
                $('#loading').show();
                $('#btnSearch').prop("disabled", true);
                table = $('#SearchResultTable').DataTable({

                    searching: false,
                    "proccessing": true,
                    "serverSide": true,
                    "aaSorting": [],

                    "ajax": {

                        data: function (d) {
                            d.UserName = UserName;
                            d.StartDate = StartDate;
                            d.EndDate = EndDate;
                            d.change = Parachanged;
                        },
                        url: "@Url.Action("CustomerAccountLogTable", "Report")",
                        type: 'POST',
                    },
                    "drawCallback": function (settings) {
                        changed = "F";
                        Parachanged = changed;
                        $('#SearchResultTable').show();
                        if (settings.json.recordsTotal > 0)
                            $('#ToExcel').show();
                        else
                            $('#ToExcel').hide();
                        $('#loading').hide();
                        $('#btnSearch').prop("disabled", false);
                    },
                    "columns": [
                           { "data": "TranDate" },
                           { "data": "ServiceType", sortable: "false" },
                           { "data": "Amount", render: $.fn.dataTable.render.number(',', '.', 2, ''), "sClass": "text-right" },
                           { "data": "Reciver" },
                           { "data": "Description" },
                           { "data": "ResponseCode" }
                    ]
                });

            //    $('#SearchResultTable').show();
            });

            //$('#grid').on("DOMSubtreeModified", function () {
            //    changed = "F";
            //});



            $("#StartDate").datepicker(
              {
                  dateFormat: 'dd/mm/yy',
            maxDate: new Date,
                  onSelect: function (dateText) {
                      changed = "T";
                      var from = $('#EndDate').val().split("/");
                      if (from != "") {
                          var EDate = new Date(from[2], from[1] - 1, from[0]);
                          var to = dateText.split("/");
                          var SDate = new Date(to[2], to[1] - 1, to[0]);;
                          if (SDate > EDate) {
                              $('#EndDate').val("");
                              $('#message').text('End Date cannot be less than Start Date');
                          }
                          else {
                              $('#message').text("");
                          }
                      }
                  }
              });

            $("#EndDate").datepicker(
             {
                 dateFormat: 'dd/mm/yy',

                 maxDate: new Date,
                 onSelect: function (dateText) {
                     changed = "T";
                     var from = $('#StartDate').val().split("/");
                     if (from != "") {
                         var SDate = new Date(from[2], from[1] - 1, from[0]);
                         var to = dateText.split("/");
                         var EDate = new Date(to[2], to[1] - 1, to[0]);;
                         if (EDate < SDate) {
                             debugger;
                             $('#EndDate').val("");
                             $('#message').text('End Date cannot be less than Start Date');
                         }
                         else {
                             $('#message').text("");
                         }
                     }
                 }
             });

            /**Validation Check */
            $('#CustomerAccountLog').bootstrapValidator({
                feedbackIcons: {
                    valid: 'glyphicon glyphicon-ok',
                    invalid: 'glyphicon glyphicon-remove',
                    validating: 'glyphicon glyphicon-refresh'
                },
                fields: {
                    UserName: {
                        validators: {
                            stringlength: {
                                min: 10,
                                max: 10,
                                message: 'Please enter valid Mobile No'

                            },
                            regexp: {
                                regexp:'^[9][8][0-9]{8}$' ,
                                message: 'Mobile no must start with 98 and should be 10 digits'

                            }
                        }
                    }


                }

            });
        });

    function isNumber(evt) {
        evt = (evt) ? evt : window.event;
        var charCode = (evt.which) ? evt.which : evt.keyCode;
        if (charCode > 31 && (charCode < 48 || charCode > 57)) {
            return false;
        }
        return true;
    }

    </script>
}

MNepalWeb/MNSuperadmin/Views/Report/SummaryDetails.cshtml
@model IEnumerable<MNSuperadmin.ViewModel.MerchantInfo>
@{
    ViewBag.Title = "SummaryDetails";
    Layout = null;

}



<!-- =============================================== -->
<!-- Content Header (Page header) -->
@*<section class="content-header">
    <h1>
        Summary
        <small>Details</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-user"></i>Summary</a></li>
        <li class="active">Summary Detail list</li>
    </ol>
</section>*@

<!-- Main content -->
<section class="content">
    <!-- Main row -->
    <div class="row">


        <!-- Start -->
        <div class="col-xs-12">
                     @{ if (Model.Count() > 0)
                         {

                            <div>No Of Transactions: @Model.Count()</div>
                            <br />
                                
                                <div class="container container-fluid" id="table" style="max-height:400px;overflow:auto;width:auto;">

                                    <table class="table table-bordered sticky-header">
                                        <thead>
                                            <tr>


                                                <th>Date And Time</th>
                                                <th>Transaction ID</th>
                                                <th>Source Mobile No</th>
                                                <th>Service Type</th>
                                                <th>Merchant Name</th>
                                                <th>Amount</th>



                                            </tr>
                                        </thead>
                                        <tbody>

                                            @foreach (var item in Model)
                                            {
                                                <tr>

                                                    <td>@item.TranDate</td>
                                                    <td>@item.TxnID</td>
                                                    <td>@item.InitMobileNo</td>
                                                    <td>@item.ServiceType</td>
                                                    <td>@item.MerchantName</td>
                                                    <td style="text-align:right">@string.Format("{0:n}",item.TotalAmount)</td>
                                                </tr>
                                            }
                                        </tbody>

                                    </table>
                                

                                </div>
                         }

                    }

                   </div>
                </div>
    </section>
                 